### ISSUE TITLE
Periodic Boundary Conditions + Dirichlet BCs

### ISSUE THREAD

**Issue by Omega-xyZac** [gridap/Gridap.jl#463] opened 2020-11-19 21:23 UTC
There seems to be issues with Dirichlet conditions when using periodic boundary. Dirichlet conditions are not applied when using `isperiodic=(true,true,true)`. See the following snippet of code:
```
nely,nelx,nelz = 3
domain = (0.0, 1, 0.0, 1, 0.0, 1);
model = CartesianDiscreteModel(domain,(nelx,nely,nelz); isperiodic=(true,true,true));

labels = get_face_labeling(model)
add_tag_from_tags!(labels,"pt_xyz_000",[1,])

V = TestFESpace(reffe=:Lagrangian, order=1, valuetype=VectorValue{3,Float64},
      conformity=:H1, model=model, dirichlet_tags=["pt_xyz_000",],
      dirichlet_masks=[(true,true,true),]);

U = TrialFESpace(V,[VectorValue(0.0, 0.0, 0.0),])

Q = TestFESpace(reffe=:Lagrangian, order=1, valuetype=Float64,
 conformity=:H1, model=model, dirichlet_tags=["pt_xyz_000",], dirichlet_masks=[true,])

Phi = TrialFESpace(Q, [0,])

VQ = MultiFieldFESpace([V, Q])
Uϕ = MultiFieldFESpace([U, Phi])

#V.ndirichlet -> 0
#Q.ndirichlet -> 0
```
Via symmetry this should lead to 8 nodes with fully constrained dofs. Instead, none of the nodes are constrained. Is this an issue with how dirichlet conditions are applied when using periodic BCs?

**Comment by Omega-xyZac** [comment] 2020-11-20 01:00
Work around possible using
```
entity = num_entities(labels) + 1
labels.d_to_dface_to_entity[1][1] = entity
add_tag!(labels,"pt_xyz_000",[entity])
```

**Comment by fverdugo** [comment] 2020-11-24 09:14
@jesusbonilla have you ever tried periodic BCs in all directions ?

**Comment by jesusbonilla** [comment] 2020-11-24 15:17
Yes, I have tried periodic BC in all directions. I have not tried to add Dirichlet BC and Periodic BC at the same time.

If I understand properly @Omega-xyZac's issue is that without this Dirichlet condition you have your solution defined only up to a constant. Instead of fixing the value at one node manually I would use the option `constraint=:zeromean` in `TestFESpace`. The problem is that I think this constraint does not work with vector valued FE spaces.

**Comment by Omega-xyZac** [comment] 2020-11-25 00:01
Yes, the `constraint=:zeromean` does not work for a vector valued FE space: 
```

MethodError: no method matching Float64(::VectorValue{3,Float64})
Closest candidates are:
  Float64(::T) where T<:Number at boot.jl:716
  Float64(!Matched::Irrational{:catalan}) at irrationals.jl:189
  Float64(!Matched::BigFloat) at mpfr.jl:332
  ...
in top-level scope at Silva_microstructure_fig39.jl:73
in PZ_Hom at PZ_Homogenisation.jl:277
in macro expansion at base\timing.jl:174 
in PZ_FE_Hom at PZ_Homogenisation.jl:75
in  at Gridap\0VcDN\src\FESpaces\FESpaceFactories.jl:128
in #TestFESpace#4 at Gridap\0VcDN\src\FESpaces\FESpaceFactories.jl:128 
in Type##kw at Gridap\0VcDN\src\FESpaces\FESpaceFactories.jl:34 
in #FESpace#3 at Gridap\0VcDN\src\FESpaces\FESpaceFactories.jl:91
in ZeroMeanFESpace at Gridap\0VcDN\src\FESpaces\ZeroMeanFESpaces.jl:26
in _setup_vols at Gridap\0VcDN\src\FESpaces\ZeroMeanFESpaces.jl:38
in assemble_vector at Gridap\0VcDN\src\FESpaces\Assemblers.jl:126
in assemble_vector! at Gridap\0VcDN\src\FESpaces\SparseMatrixAssemblers.jl:27 
in assemble_vector_add! at Gridap\0VcDN\src\FESpaces\SparseMatrixAssemblers.jl:188
in _assemble_vector! at Gridap\0VcDN\src\FESpaces\SparseMatrixAssemblers.jl:198
in _assemble_vector_at_cell! at Gridap\0VcDN\src\FESpaces\SparseMatrixAssemblers.jl:206 
in add_entry! at Gridap\0VcDN\src\Algebra\AlgebraInterfaces.jl:92
in add_entry! at Gridap\0VcDN\src\Algebra\AlgebraInterfaces.jl:93
in setindex! at base\array.jl:847
in convert at base\number.jl:7
```
Unfortunately, I need this constraint for two FE spaces:
```
V = TestFESpace(reffe=:Lagrangian, order=1, valuetype=VectorValue{3,Float64},
         conformity=:H1, model=model, constraint=:zeromean)
```
and 
```
Q = TestFESpace(reffe=:Lagrangian, order=1, valuetype=Float64,
         conformity=:H1, model=model, constraint=:zeromean)
```

**Comment by santiagobadia** [comment] 2020-11-25 00:27
I am not sure there is any issue related to the periodic boundary conditions. As @jesusbonilla says, I guess you are solving a differential operator with some kernel that is not being fixed with periodic boundary conditions. You need to add constraints to make your problem non-singular. If the kernel is a constant in each space, you can just enforce the value (of all vector components) in a node of the mesh for both spaces. If it is more than that (e.g., linear elasticity in 3D) you would need to add more constraints. 

Internally, zeromean is doing this. As the name suggests, it enforces a zero mean for a scalar field but it is unclear what it means for vector fields. A better solution is just to look at zeromean and extend it to vector-valued spaces (i.e., enforcing the constraint for all components), such that zeromean for vector spaces provides zeromean for all components. I think it should be quite simple.

In any case, probably, the final solution is something different (more involved) that I will write in another issue.

**Comment by Omega-xyZac** [comment] 2020-11-25 01:14
Okay, I will look into this. 

I'll flesh out my problem for you as well. In this problem I am solving microstructure homogenisation for linear piezoelectricity. Usually, one can simply constrain a single vertex for all DOFs (3 dis + 1 electric) and via the PBCs this is applied to the other vertices.

**Comment by Omega-xyZac** [comment] 2020-11-25 05:05
I might need some guidance on extending zero mean to vector-valued spaces. It seems that the extension is required in `_setup_vols(V,trian,quad)`.

**Comment by Omega-xyZac** [comment] 2020-11-25 06:27
I think a way around this for Cartesian grids is the following:
```
V = TestFESpace(reffe=:Lagrangian, order=1, valuetype=VectorValue{3,Float64},
         conformity=:H1, model=model)#, constraint=:zeromean)#,

  VFixed = FESpaceWithConstantFixed(V,true,num_free_dofs(V))
  trian = Triangulation(model)
  quad = CellQuadrature(trian,2)
  U = TrialFESpace(V)
  assem = SparseMatrixAssembler(U,V)
  bh = get_cell_basis(V)
  bh_trian = restrict(bh,trian)
  cellvec = integrate(bh_trian,trian,quad)
  cellvec=fill(fill(cellvec[1][1][1],24),length(cellvec))
  cellids = get_cell_id(trian)
  vol_i = assemble_vector(assem,vecdata)
  vol = sum(vol_i)
  V = ZeroMeanFESpace(VFixed,vol_i,vol,constraint_style(VFixed))
```
Strangely, this gives the same value as the Dirichlet BC. Thoughts?

**Closed** 2021-07-15 22:02 UTC
