### ISSUE TITLE
joss-paper: Build tutorials not described

### ISSUE THREAD

**Issue by PetrKryslUCSD** [gridap/Gridap.jl#336] opened 2020-07-26 23:19 UTC
The readme does not describe how to get the tutorial notebooks opened from a cloned  repository. In particular, when the repository is cloned, there are no notebooks. They need to be built. The build step is not documented. It appears to be activate/instantiate/build. 
Then one can open a notebook with `IJulia.notebook()`.

**Comment by fverdugo** [comment] 2020-07-27 12:33
Related to  https://github.com/openjournals/joss-reviews/issues/2520

**Comment by fverdugo** [comment] 2020-07-28 15:18
@PetrKryslUCSD The steps to clone, build and open the notebooks of the Gridap tutorials are explained in the documentation pages of the tutorials repository https://gridap.github.io/Tutorials/stable/

In the read-me file of https://github.com/gridap/Tutorials there is a link to the documentation pages. Do you believe this is not enough?

**Comment by PetrKryslUCSD** [comment] 2020-07-28 15:30
My

**Comment by PetrKryslUCSD** [comment] 2020-07-28 15:33
My comment was based on the order in which the user would proceed. If I start with the readme, follow the link to the stable version of the tutorials, and click on the first tutorial I can see how to run it in the mybinder, but I don't know how to run it on my own machine.  So I go back to the readme.

Honestly, I missed the description that is below the list of tutorials. My bad. But I think it points to a possible reorganization where the documentation of the tutorials starts with instructions on how to run them, and then follows the list of tutorials.

Just a suggestion.

**Comment by fverdugo** [comment] 2020-08-05 13:24
Perhaps the problem is that the instructions on how to build the notebooks are not in the section called **How to start**.

https://gridap.github.io/Tutorials/stable/#How-to-start-1

I'll try to fix this.

**Comment by fverdugo** [comment] 2020-08-05 16:24
Hi @PetrKryslUCSD 

I have rewritten the confusing part. I hope that now it is better:

https://gridap.github.io/Tutorials/v0.12/

If you are happy with the changes, please close the issue.

Thanks!

**Closed** 2020-08-05 17:08 UTC
