### ISSUE TITLE
Add div conforming elements to new functionality

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#177] opened 2020-02-06 01:27 UTC
Hi @fverdugo 

I have been working in the RT reference FE in the branch I created for such purpose.

You can find in [this](https://github.com/gridap/Gridap.jl/blob/div-conforming-ref-fe/test/ReferenceFEsTests/DivRefFEsTests.jl) test file the implementation. 

You can see that I am including the implementation right in the test [here](https://github.com/gridap/Gridap.jl/blob/a7e75a018c52a14e1f05c6d1fefeee733ba14f52/test/ReferenceFEsTests/DivRefFEsTests.jl#L14), because there is a cycle. I do need integration but the polytope is now in the `ReferenceFE` module. We should break this cycle.

The missing part is the creation of the reference FE [here](https://github.com/gridap/Gridap.jl/blob/a7e75a018c52a14e1f05c6d1fefeee733ba14f52/test/ReferenceFEsTests/DivRefFEsTests.jl#L55). This part should be simple, just to create the struct and implement the API.

I am not sure about the name, the file is called `MomentReferenceFEs` and I am using `GenericReferenceFE` in the code. We should discuss the `ReferenceFE` hierarchy, put the name you like for the moment. In any case, I think that the hierarchy does not affect users, so we can proceed without it being in final version.

Now you have `NodalReferenceFE`. Are RT or Nedelec nodal? These methods are associated to nodal values per faces (in general sense), they need similar permutations, evaluation on nodes, etc. The only difference is that they do require to combine these nodal values to get moments. If your def of nodal is *dofs are just node values* they are not but not sure this restricted def'on is a good idea.

What is more relevant in my opinion is the fact that these ref FEs are not based on Cartesian product of scalar spaces. That is probably a more important feature to consider in our hierarchy. CartesianProduct spaces and genuinely vector (tensor) spaces...

By the way, I have put all what I need to implement RT in one file. Some methods can be moved later to other parts of the code...

**Comment by fverdugo** [comment] 2020-02-06 07:15
> You can see that I am including the implementation right in the test here, because there is a cycle. I do need integration but the polytope is now in the ReferenceFE module. We should break this cycle.

I'll take a look to this!

> I am not sure about the name, the file is called MomentReferenceFEs and I am using GenericReferenceFE in the code. We should discuss the ReferenceFE hierarchy, put the name you like for the moment. In any case, I think that the hierarchy does not affect users, so we can proceed without it being in final version.

There are several ways of organizing the hierarchy, but as you say, this is not very crucial in practice. Its even possible to reuse code in the implementation of moment-based reffes like RT and Nedelec by using common helper functions instead touching the reffe hierarchy.  Perhaps, I would use concrete structs (that possibly wrap a `GenericReferenceFE`) with the concrete name of the the element you are implementing (`RaviartThomasRefFE`, `NedelecRefFE `) just to be more informative. But, as you prefer, I don't have strong feelings here. 

>Now you have NodalReferenceFE. Are RT or Nedelec nodal? These methods are associated to nodal values per faces (in general sense), they need similar permutations, evaluation on nodes, etc. The only difference is that they do require to combine these nodal values to get moments. If your def of nodal is dofs are just node values they are not but not sure this restricted def'on is a good idea.
>
>What is more relevant in my opinion is the fact that these ref FEs are not based on Cartesian product of scalar spaces. That is probably a more important feature to consider in our hierarchy. CartesianProduct spaces and genuinely vector (tensor) spaces...

At the moment, `NodalReferenceFE` are reffes whose dofs are asociated with some specific locations in space (i.e. nodes).  This is only used for visualization purposes (very useful for debugging, teaching, etc..., but completely irrelevant in other parts of the code). If you implement the `NodalReferenceFE` interface, you will able to write the reffe to vtk with info about the node vs dof relation. E.g.

```julia
using Gridap.ReferenceFEs
using Gridap.Visualization
reffe = PDiscRefFE(VectorValue{2,Float64},HEX,4)
writevtk(reffe,"reffe")
```

![dofx](https://user-images.githubusercontent.com/48508177/73913531-9721a100-48b7-11ea-9044-8f20924684bb.png)


> What is more relevant in my opinion is the fact that these ref FEs are not based on Cartesian product of scalar spaces. That is probably a more important feature to consider in our hierarchy. CartesianProduct spaces and genuinely vector (tensor) spaces...

I think its not needed to introduce more abstract types in the reffe hierarchy for the moment. I would only add them if they are required to write generic code in terms of this abstract type in other parts later in the library. Now, we have:

- `Gridap.Geometry` written in terms of `LagrangianRefFE`
- `Gridap.FESpaces` written in terms of `ReferenceFE`
- `Gridap.Visualization` written in terms of  `NodalReferenceFE`

**Comment by fverdugo** [comment] 2020-02-06 08:36
@santiagobadia 

I think that the module cycle is caused by the calls
```julia
  fquad = Quadrature(fp,degree)
  fips = get_coordinates(fquad)
  wips = get_weights(fquad)
```
This is easy to fix. I will re-structure a little bit the code to breack the cycle.

I let you know when the fix is ready.

**Comment by santiagobadia** [comment] 2020-02-06 09:05
I understand from your comment that RT and Nedelc are NodalReferenceFE because you can relate Dofs to nodes.

Yes, the cycle is due to the need to use the quadrature in the integration of moments and the fact that the quadrature module depens on Polytope...

**Comment by fverdugo** [comment] 2020-02-06 09:33
I have isolated the quadrature rules in branch `isolate_quadrature_rules`.

You can do:
```
$ git checkout div-conforming-ref-fe
$ git pull origin isolate_quadrature_rules
```
and check if the cycles is solved

**Comment by fverdugo** [comment] 2020-02-12 10:12
Hi @santiagobadia 

In PR #185, I have finished the implementation of Raviart-Thomas spaces

I have found some bugs in the code you provided (e.g., the DOF basis returned arrays larger than in Gridap v0.5.2). I have tried to solve these bugs by myself, but I cannot ensure that I have fixed them properly. 

I think, there is still some subtle issue. Consider this example, where I interpolate the function u(x) = x into a RT-space:

```julia
using Gridap.FESpaces
using Gridap.Geometry
using Gridap.ReferenceFEs
using Gridap.Visualization

domain =(0,1,0,1)
partition = (3,3)
model = CartesianDiscreteModel(domain,partition)
trian = get_triangulation(model)

V = TestFESpace(
  reffe = :RaviartThomas,
  conformity = :Hdiv,
  order = 2,
  model = model,
  dirichlet_tags = [1,6])

u(x) = x
U = TrialFESpace(V,u)

uh = interpolate(U,u)

writevtk(trian,"trian",nsubcells=10,cellfields=["uh"=>uh])

```

When I plot the x1-component of the interpolated field, I get:
![hdiv](https://user-images.githubusercontent.com/48508177/74325103-5da1d780-4d88-11ea-96a5-b547ecccce7f.png)


This is not correct, right?

**Comment by fverdugo** [comment] 2020-02-12 10:41
FYI, I have merged PR #185 into master and deleted the branch div-conforming-ref-fe

We can open a new branch to fix the remaining issues.

**Comment by fverdugo** [comment] 2020-02-12 12:18
I think the problem is in the dof basis (perhaps in the face moments). I get different results with the current version and v0.5.2:

Current version:
```julia
using Gridap
using Gridap.ReferenceFEs

reffe = RaviartThomasRefFE(Float64,QUAD,1)
evaluate(get_dof_basis(reffe),get_prebasis(reffe))

#output
4×4 Array{Float64,2}:
  0.0  -1.0  0.0  0.0
  0.0   1.0  0.0  1.0
 -1.0   0.0  0.0  0.0
  1.0   0.0  1.0  0.0
```
In Gridap@0.5.2
```julia
using Gridap

p = Polytope(HEX_AXIS,HEX_AXIS)
reffe = RaviartThomasRefFE(p,1)
prebasis = CurlGradMonomialBasis(VectorValue{2,Float64},1)
evaluate(reffe.dof_basis,prebasis)

#output 
4×4 Array{Float64,2}:
 0.0  0.0  -1.0  -1.0
 1.0  1.0   0.0   0.0
 0.0  0.0   0.0  -1.0
 0.0  1.0   0.0   0.0
```

The two matrices should be one the transpose of the other (change of criterion between the two versions), and are not!

**Comment by fverdugo** [comment] 2020-02-13 10:35
I have spotted the error. It is in line
https://github.com/gridap/Gridap.jl/blob/e6bfbda1bc273b5279b9deff2ae9ba081d49dbc4/src/ReferenceFEs/RaviartThomasRefFEs.jl#L93

One needs to use the code commented in the line before
https://github.com/gridap/Gridap.jl/blob/e6bfbda1bc273b5279b9deff2ae9ba081d49dbc4/src/ReferenceFEs/RaviartThomasRefFEs.jl#L92

When using the facet orientation everything OK

```julia
using Gridap
using Gridap.ReferenceFEs

reffe = RaviartThomasRefFE(Float64,QUAD,1)
evaluate(get_dof_basis(reffe),get_prebasis(reffe))

#output
4×4 Array{Float64,2}:
  0.0  1.0   0.0  0.0
  0.0  1.0   0.0  1.0
 -1.0  0.0   0.0  0.0
 -1.0  0.0  -1.0  0.0
```
![hdiv](https://user-images.githubusercontent.com/48508177/74425962-d0788480-4e54-11ea-8680-34bbce309923.png)

I'm going to open a PR with the fix.

**Comment by fverdugo** [comment] 2020-02-13 10:39
I assume that this hack with the facet orientations has to be removed once the RT-space is extended for meshes different from structured Cartesian ones, right?

**Comment by fverdugo** [comment] 2020-02-13 15:46
I close the issue. We can always open another to discuss the extension to non-cartesian meshes.

**Closed by fverdugo** 2020-02-13 15:46 UTC
